// GENERATED by `node scripts/check-ga-baseline-drift.mjs --write` — do not edit.
// Source of truth: managed-ga/manifest.json (`upstream` block). The drift
// gate (CI) fails when this file disagrees with the manifest.

/** Audited upstream GenericAgent commit (full SHA). */
export const GA_BASELINE_COMMIT = "f06d5503808ba9d164fb583e4c500d5ce01efd4c";

/** Committer date of GA_BASELINE_COMMIT (`git log -1 --format=%cI`). */
export const GA_BASELINE_COMMIT_DATE = "2026-08-13T10:19:48+08:00";
