// GENERATED by `node scripts/check-ga-baseline-drift.mjs --write` — do not edit.
// Source of truth: managed-ga/manifest.json (`upstream` block). The drift
// gate (CI) fails when this file disagrees with the manifest.

/** Audited upstream GenericAgent commit (full SHA). */
export const GA_BASELINE_COMMIT = "308153b1c91401a892401dd896e548e587506cc9";

/** Committer date of GA_BASELINE_COMMIT (`git log -1 --format=%cI`). */
export const GA_BASELINE_COMMIT_DATE = "2026-08-10T14:02:51+08:00";
