// GENERATED by `node scripts/check-ga-baseline-drift.mjs --write` — do not edit.
// Source of truth: managed-ga/manifest.json (`upstream` block). The drift
// gate (CI) fails when this file disagrees with the manifest.

/** Audited upstream GenericAgent commit (full SHA). */
export const GA_BASELINE_COMMIT = "4086d5c858b90e10eb24a106ea3c41ac729bc00e";

/** Committer date of GA_BASELINE_COMMIT (`git log -1 --format=%cI`). */
export const GA_BASELINE_COMMIT_DATE = "2026-07-23T15:30:36+08:00";
