import { readFileSync, writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { assistantRowFromTurnEnd } from "@/test/assistant-row";
import type { TurnEndEvent } from "@/types/ipc";

// Shared golden fixtures for Core-owned turn persistence (2026-10-07).
// Core writes the assistant row with a Rust port of the GUI's turn_end
// derivation (core/src/turn_persistence/derive.rs); cargo test asserts
// the same two files. Inputs are hand-authored; rows are generated from
// the GUI's live derivation:
//
//   GALLEY_UPDATE_TURN_GOLDEN=1 pnpm --dir gui test turn-persistence
//
// Regenerate after a deliberate change to the TS derivation, then make
// the Rust port match (cargo test fails until it does).

const FIXTURES = "../../../core/tests/fixtures/";
const CASES_URL = new URL(
  `${FIXTURES}turn-persistence-cases.json`,
  import.meta.url,
);
const ROWS_URL = new URL(
  `${FIXTURES}turn-persistence-rows.json`,
  import.meta.url,
);

interface GoldenCase {
  name: string;
  turnEnd: Omit<TurnEndEvent, "kind">;
}

/**
 * Re-key objects in the order Core serializes them: a runner's JSON
 * lives in Core as `serde_json::Value`, whose maps (no `preserve_order`
 * feature) iterate sorted by the keys' UTF-8 bytes. A page receives
 * that order, so the fixture's hand-written key order must not leak in.
 */
function asCoreEmits(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(asCoreEmits);
  if (value === null || typeof value !== "object") return value;
  const keys = Object.keys(value).sort((a, b) =>
    Buffer.compare(Buffer.from(a, "utf8"), Buffer.from(b, "utf8")),
  );
  const out: Record<string, unknown> = {};
  for (const key of keys) {
    out[key] = asCoreEmits((value as Record<string, unknown>)[key]);
  }
  return out;
}

// JSON.parse, the way the webview parses Core's runner-event payload:
// literals like 30.0 or 1e21 and integer-like keys come out exactly as
// a live page sees them.
const cases = (
  JSON.parse(readFileSync(CASES_URL, "utf8")) as { cases: GoldenCase[] }
).cases;

const derived = Object.fromEntries(
  cases.map((c) => [
    c.name,
    assistantRowFromTurnEnd({
      kind: "turn_end",
      ...(asCoreEmits(c.turnEnd) as GoldenCase["turnEnd"]),
    }),
  ]),
);

describe("turn persistence golden rows (shared with cargo test)", () => {
  if (process.env.GALLEY_UPDATE_TURN_GOLDEN) {
    it("regenerates turn-persistence-rows.json from the live derivation", () => {
      const file = {
        about:
          "GENERATED by gui/src/lib/turn-persistence.golden.test.ts from the GUI's live turn_end derivation - do not edit. Inputs: turn-persistence-cases.json.",
        rows: derived,
      };
      writeFileSync(ROWS_URL, `${JSON.stringify(file, null, 2)}\n`);
    });
    return;
  }

  const golden = (
    JSON.parse(readFileSync(ROWS_URL, "utf8")) as {
      rows: Record<string, unknown>;
    }
  ).rows;

  it("has a generated row for every case and no stale ones", () => {
    expect(Object.keys(golden).sort()).toEqual(cases.map((c) => c.name).sort());
  });

  it.each(cases.map((c) => c.name))("%s", (name) => {
    expect(derived[name]).toEqual(golden[name]);
  });
});
